### ISSUE TITLE
Default Parameter for convolution layer in import caffe

### ISSUE THREAD

**Issue by tzzcl** [vlfeat/matconvnet#595]
When I try to transform caffe model into MatConvNet file.

for caffe variant = caffe_b590f1d
I get this error:
```

Traceback (most recent call last):
  File "import-caffe.py", line 560, in <module>
    cmodel.reshape()
  File "~/matconvnet/utils/layers.py", line 1049, in reshape
    layer.reshape(self)
  File "~/matconvnet/utils/layers.py", line 397, in reshape
    self.pad) \
  File "~/matconvnet/utils/layers.py", line 51, in getFilterOutputSize
    return [floor((size[0] + pad[0]+pad[1] - kernelSize[0]) / stride[0]) + 1., \

```

When I solved this issue later.

I just find that for this caffe-variant.

we need to add all default caffe parameters in the prototxt.

for example: `pad:1 and others`

So can anyone fix this issues?

**Comment by ieted** [comment]
Hi @tzzcl , I met the same issue, could you please share more details about how you solved it? _"we need to add all default caffe parameters in the prototxt. for example: pad:1 and others"_ is still not very clear to me.

**Comment by tzzcl** [comment]
@ieted to solve this problem,
first
set caffe variant = caffe_b590f1d(same format to newest caffe prototxt).

then, in network prototxt,

for each convolution layer:

check whether following attributes are existing, if not, add default parameters:
```
    num_output
    pad
    stride
    kernel_size
```

That the import-caffe.py will work!

**Comment by ieted** [comment]
Thanks @tzzcl ! Now everything works perfect. You saved my day :)
