### ISSUE TITLE
Importing error with the latest Caffe model

### ISSUE THREAD

**Issue by ieted** [vlfeat/matconvnet#622]
I was trying to import a pre-trained Caffe model (on Places 365 dataset, see [this page](https://github.com/metalbubble/places365)) and convert it to .mat format for further use. However, I got the following error using the script import-caffe.py.
$ python import-caffe.py --caffe-data="alexnet_places365.caffemodel" "deploy_alexnet_places365.prototxt" "./alex.mat"

Caffe varaint set to caffe
Loading Caffe CNN structure from deploy_alexnet_places365.prototxt
Traceback (most recent call last):
  File "import-caffe.py", line 326, in <module>
    google.protobuf.text_format.Merge(args.caffe_proto.read(), net)
  File "/data1/runtime/anaconda2/lib/python2.7/site-packages/protobuf-3.0.0b3-py2.7.egg/google/protobuf/text_format.py", line 369, in Merge
    allow_field_number)
  File "/data1/runtime/anaconda2/lib/python2.7/site-packages/protobuf-3.0.0b3-py2.7.egg/google/protobuf/text_format.py", line 411, in MergeLines
    return parser.MergeLines(lines, message)
  File "/data1/runtime/anaconda2/lib/python2.7/site-packages/protobuf-3.0.0b3-py2.7.egg/google/protobuf/text_format.py", line 440, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/data1/runtime/anaconda2/lib/python2.7/site-packages/protobuf-3.0.0b3-py2.7.egg/google/protobuf/text_format.py", line 455, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/data1/runtime/anaconda2/lib/python2.7/site-packages/protobuf-3.0.0b3-py2.7.egg/google/protobuf/text_format.py", line 524, in _MergeField
    message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 7:1 : Message type "caffe.NetParameter" has no field named "layer".

Any suggestion on how to solve it? Thanks in advance.

**Comment by ieted** [comment]
Solved by specify the caffe-variant option to caffe_b590f1d before running the script.
